#!/usr/bin/env ruby

begin
  ENV['BUNDLE_GEMFILE'] = File.expand_path('Gemfile', __dir__)
  ENV['BOT_POLLER_MODE'] = 'true'
  require_relative 'config/environment'
  Telegram::Bot::UpdatesPoller.start(:default)
  p 'success'
rescue Exception => e
  Rollbar.report_exception(e) if defined?(Rollbar) && !e.is_a?(SystemExit)
  raise
end
